### ISSUE TITLE
What was the motivation to.make this awesome lib

### ISSUE THREAD

**Issue by MahmoudMabrok** [TarekkMA/scoped_get_it#1]

**Comment by TarekkMA** [comment]
Thank you, Mahmoud, for your questions. This library is built on top of the get_it library and it aims to provide scopes to it.

Right now in get_it you only have 2 options either a factory registration or a singleton registration, but you will sometime need some dependency to behave like singletons only in a cretin scope of the widget tree. It is a similar approach to provider but works with get_it.
