### ISSUE TITLE
Just to let you know, I will add scopes to GetIt now :-)

### ISSUE THREAD

**Issue by escamoteur** [TarekkMA/scoped_get_it#2]

**Comment by escamoteur** [comment]
V5.0.0 now supports scopes.

**Comment by TarekkMA** [comment]
really loves it 💖♥️

**Comment by escamoteur** [comment]
Thanks. I hope you were not too disappointed that your package got obsolete with this.
I'm currently working on another nice thing. a mixin to bind objects in GetIt to the UI much like Hooks or provider do it

**Comment by TarekkMA** [comment]
not at all. you did the right thing 💖 now this package had fulfilled its job 😁 making you implement scopes.

I will archive this package and add a note linking to get_it and it's scopes.

Thank you
